### ISSUE TITLE
Problemas con la configuración en el fine tunning del modelo (falcon_7b_finetune_psycologyst_assistant.ipynb)

### ISSUE THREAD

**Issue by vicbguti29** [RobertoPatino1/L.U.C.Y#1]
![image](https://github.com/RobertoPatino1/Proyecto_PreTAWS_G4/assets/133924738/7aedc568-4695-455e-8b91-a2ce10596fa6)

**Comment by vicbguti29** [comment]
![image](https://github.com/RobertoPatino1/Proyecto_PreTAWS_G4/assets/133924738/8df9d8a8-a5b6-4317-be13-435a92859e2d)
Pienso que puede ser el optim.

**Comment by RobertoPatino1** [comment]
Mira este issue: [https://github.com/huggingface/transformers/issues/23336](url)
